Vagrant.configure("2") do |config|
  # which vagrant box to use
  config.vm.box = "centos"
  # download box
  config.vm.box_url = "https://github.com/2creatives/vagrant-centos/releases/download/v6.4.2/centos64-x86_64-20140116.box"
  # mount local folder with nfs
  config.vm.synced_folder ".", "/vagrant", type: "nfs"
  # set eth1
  config.vm.network "private_network", ip: "172.16.0.254"
  # add provisioning script
  config.vm.provision "shell", path: "basic.sh"
end
